CREATE TABLE IF NOT EXISTS user_accounts (
    user_account_id BIGINT PRIMARY KEY,
    account_type VARCHAR(50) DEFAULT 'Standard',
    account_username VARCHAR(100) NOT NULL,
    account_password VARCHAR(255) NOT NULL,
    account_email VARCHAR(150) NOT NULL,
    in_country VARCHAR(100),
    user_time_zone VARCHAR(50),
    selected_language VARCHAR(50),
    user_gender VARCHAR(10),
    user_birthday DATE,
    user_age INT,
    is_online BOOLEAN DEFAULT FALSE,
    last_online_time TIMESTAMP,
    is_playing BOOLEAN DEFAULT FALSE,
    is_in_queue BOOLEAN DEFAULT FALSE,
    ban_reason TEXT,
    is_banned BOOLEAN DEFAULT FALSE,
    ban_time_stamp TIMESTAMP,
    account_creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    num_kills INT DEFAULT 0,
    num_deaths INT DEFAULT 0,
    kill_death_ratio DOUBLE PRECISION DEFAULT 0.0,
    num_games_played INT DEFAULT 0,
    num_games_won INT DEFAULT 0,
    num_games_lost INT DEFAULT 0,
    num_games_tied INT DEFAULT 0,
    win_percentage DOUBLE PRECISION DEFAULT 0.0,
    user_level INT DEFAULT 1,
    current_level_xp BIGINT DEFAULT 0,
    required_level_up_xp BIGINT DEFAULT 100,
    gem_balance BIGINT DEFAULT 0,
    profile_picture_path TEXT
    );
